[tool.poetry]
name = "gol-baby-test"
version = "0.1.0"
description = ""
authors = ["eb-pagos <endrit.bytyqi@pagos.ai>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
